[book]
title = "AxiaPanel Documentation"
authors = ["AxiaPanel"]
language = "en"
src = "."

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/ovexro/axiapanel"
